kind: pipeline
type: docker
name: default

# 定义全局环境变量
environment:
  APP_PORT: 16140

volumes:
  - name: maven-cache
    host:
      path: /volume2/docker/drone/server-01/drone-runner-docker/maven-cache
  - name: run-script
    host:
      path: /volume2/docker/drone/server-01/drone-runner-docker/apps/java/run-script
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
    - name: 构建
      image: maven:3.8-openjdk-11
      pull: if-not-exists
      volumes:
        - name: maven-cache
          path: /root/.m2
        - name: run-script
          path: /app/build
      commands:
        - pwd
        - mvn clean install
        - mkdir -p /app/build/${DRONE_REPO_NAME} && rm -rf /app/build/${DRONE_REPO_NAME}/*
        - mkdir -p /app/build/${DRONE_REPO_NAME} && find . -type f -name "*.jar" -path "*/target/*" -exec cp {} /app/build/${DRONE_REPO_NAME} \;
        - mkdir -p /app/build/${DRONE_REPO_NAME} && cp -R ./*.sh /app/build/${DRONE_REPO_NAME}/
        - mkdir -p /app/build/${DRONE_REPO_NAME} && cp -R ./Dockerfile /app/build/${DRONE_REPO_NAME}/
    - name: 部署
      image: plugins/docker
      volumes:
        - name: run-script
          path: /app/build
        - name: docker
          path: /var/run/docker.sock # 挂载宿主机的docker
      settings:
        dockerfile: /app/build/${DRONE_REPO_NAME}/Dockerfile
      commands:
        - cd /app/build/${DRONE_REPO_NAME}/
        - ls -al /app/build/${DRONE_REPO_NAME}/
        - chmod +x run-docker.sh
        - /app/build/${DRONE_REPO_NAME}/run-docker.sh
        - docker ps
    - name: 构建通知
      image: plugins/webhook
      pull: if-not-exists
      settings:
        urls: https://oapi.dingtalk.com/robot/send?access_token=d23bb0bb02a1253f5fa8e5be917fb8f0798580df63dcf83f6a97ef08b9fee3e5
        content_type: application/json
        template:
          {
            "msgtype": "markdown",
            "markdown": {
              "title": "构建通知",
              "text": "{{#success build.status}}{{else}}{{/success}}**{{repo.owner}}/{{repo.name}}**\n
> **构建结果**: {{build.status}}\n
> **构建详情**: [点击查看]({{build.link}})\n
> **代码分支**: {{build.branch}}\n
> **提交标识**: {{build.commit}}\n
> **提交发起**: {{build.author}}\n
> **提交信息**: {{build.message}}"
            }
          }
trigger:
  branch:
    - master